project:
  type: website
  preview:
    # port: 3000
    browser: false

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 4

website:
  twitter-card: true
  open-graph: true
  repo-actions: [issue]
  sidebar:
    style: floating
    contents:
      # - auto: "/*.ipynb"
      - section: AIMS
        contents: "aims/*.qmd"
      - section: DATA
        contents: "data.qmd"
      - section: APPS
        contents: "apps/*.qmd"
  favicon: images/favicon.png
  navbar:
    background: primary
    search: true
    collapse-below: lg
    left:
      - text: "AIMS"
        menu:
          - text: "Aim 1:xxx"
            href: AIMS/Aim1.qmd
          - text: "Aim 2:xxx"
            href: AIMS/Aim2.qmd
          - text: "Aim 3:xxx"
            href: AIMS/Aim3.qmd
          - text: "Aim 4:xxx"
            href: AIMS/Aim4.qmd
      - text: "DATA"
        href: data.qmd
      - text: "AIMS"
        menu:
          - text: "survmaximin"
            href: APPS/1_survmaxmin.qmd
          - text: "ARCH"
            href: APPS/2_ARCH.qmd
          - text: "KESER"
            href: APPS/3_KESER.qmd
    right:
      - icon: github
        href: "https://github.com/fastai/nbdev"
      - icon: twitter
        href: https://twitter.com/fastdotai
        aria-label: Fast.ai Twitter

metadata-files: [csrp.yml]

